bandersnatch/precomp_multiexp.go
ipa/config.go
ipa/ipa_test.go

Generating the precomputation tables for the Lagrange points takes a lot of time. This causes geth to be seemingly idle for 2 to 5 minutes, giving the impression that a problem occurred. This is true, even if the verkle tree isn't activated in geth. This is a show-stopper for merging the geth PR.
As a mitigation strategy, I'd like to be able to generate it only once, and then store that data to the database, to be reloaded later. This PR therefore adds a `DeserializePrecomputedLagrange` function, that can be used to load said precomputed points from the database.
**Trigger Warning**: contains AmericaniZed (AmericaniZee?) spelling.

add (de)serialization methods to the precomputation tables

---

bandersnatch/multiexp.go
bandersnatch/point.go
bandersnatch/precomp_multiexp.go
ipa/srs_precomp.go

This PR contains a set of optimizations that improves the performance of the library significantly.
Using the reference benchmarks in the repo, here's a comparison in performance between `master` and this PR:
```
name                           old time/op    new time/op    delta
pkg:github.com/crate-crypto/go-ipa/bandersnatch goos:linux goarch:amd64
MultiExpG1/32_points-16           318µs ± 6%     355µs ±11%   +11.81%  (p=0.000 n=10+8)
MultiExpG1/64_points-16           354µs ± 5%     287µs ± 4%   -18.69%  (p=0.000 n=10+7)
MultiExpG1/128_points-16          450µs ± 5%     381µs ± 6%   -15.31%  (p=0.000 n=10+8)
MultiExpG1/256_points-16          649µs ± 4%     556µs ± 5%   -14.31%  (p=0.000 n=10+8)
MultiExpG1/512_points-16         1.04ms ± 4%    0.87ms ± 2%   -16.34%  (p=0.000 n=9+8) …
```

Avoid allocs improving ~15% performance and using ~97% less memory

---

bandersnatch/fr/element.go

This should be slightly faster, omitting one borrow from the integer pool. 
Just getting familiar with the code, really.

fr: some minor opimizations

---

bandersnatch/fr/element.go

Comparing against a zero-initialized big.Int is semantically the same as checking `Sign`

bandersnatch/fr: remove bigint zero

---

bandersnatch/fp/arith.go
bandersnatch/fp/element.go

This PR updates our `(*Element).Inverse(...)` implementation with a newer version of `goff` generated code. `goff` is a CLI tool from [gnark-crypto](https://github.com/ConsenSys/gnark-crypto/tree/master/field/goff) that is used to generate Go ECC implementations of different curves (e.g: [their BLS12-381 implementation](https://github.com/ConsenSys/gnark-crypto/tree/master/ecc/bls12-381)).
So I ran `go run ./field/goff -m 52435875175126190479447740508185965837690552500527637822603658699938581184513 -o go-ipa-bls -p fr -e Element`, and got the new version of the implementation.
I focused only in manually porting the `(*Element).Inverse(...)` new version for multiple reasons:
- I wanted to change as few lines as possible in `go-ipa`.
- I wanted to keep all the existing tests, since changing …

bandersnatch/fp: more performant Inv implementation

---

banderwagon/element.go
banderwagon/element_test.go

Change APIs and preallocate slices of known length to avoid allocations in:
- Group to Field transformation.
- Multi Group to Field transformation.
- ElementToBytes.

banderwagon: avoid allocations in scalar field conversions

---

banderwagon/precomp_multiexp.go
ipa/config.go

This PR avoids a forced heap allocation since it avoids returning a pointer from a stack variable. This was noticed while looking at profiling information in `go-verkle`.
It also removes an unnecessary assignment.
Linked to https://github.com/gballet/go-verkle/pull/314

Avoid forced heap escaping for polynomial commitment

---

bandersnatch/fp/sqrt.go
bandersnatch/fp/sqrt_test.go
bandersnatch/point.go

This PR includes optimization for sqrt. 
My approach here is to make the minimal changes from the [Bandersnatch repo](https://github.com/GottfriedHerold/Bandersnatch) implementation so we can take advantage of the speedup as soon as possible.
Upstreaming this to gnark is a separate beast, in the sense that from what I saw it might require some refactors in their `fft` package to extract roots of unity and might not be entirely trivial. Still is a good idea to do it, but I don't want that to block our progress in the VKT speedups.
My strategy was to include this separate "faster" sqrt so that doesn't mess up with generated code from gnark, since that would be painful for us in the near future when we try to (attempt) to not depend on generated code and try using gnark directly. (Again, …

bandersnatch/fp: use optimized sqrt

---

ipa/barycentric.go

This PR batches inversions when computing barycentric coefficients.

ipa: do batch inversions for barycentric coefficients terms

---

multiproof.go

This PR batches inverses of `(t - z_i)` when calculating helper scalars.

proof verification: batch helper scalar inverses

---

banderwagon/element.go
banderwagon/element_test.go
multiproof.go

This PR creates a new helper method, `BatchNormalize([]*Element)` which is now used when generating a multiproof.
The reason is that the list `Cs` are projective points, thus when iterating over them and adding them to the transcript, the underlying `.Bytes()` will have to normalize them. That means a linear number of field inversions.
What we do now leverage the new `BatchNormalize(...)` method to normalize the projective points so when they're added to the transcript, the underlying `.Bytes()` (converting to affine) will go into fast paths avoiding inversions.
Note this situation happens for proof generation since the client has a point already in memory. For verifiers, this shouldn't be a problem since they would probably have the points in projective but deserialized from the proof, …

proof generation: batch normalize commitments for efficient transcript appending

---

ipa/barycentric.go
ipa/verifier.go
multiproof.go

This PR applies a good idea from from the [Rust implementation](https://github.com/crate-crypto/ipa_multipoint/blob/develop/src/multiproof.rs#L140).
We first aggregate the polynomials by evaluation point, and then apply the usual protocol. This avoids unnecessary heavy work in the same evaluation point.

multiproof/prover: aggregate polynomials by evaluation point

---

multiproof.go

This PR fixes a bug identified by running `go-verkle` compatibility tests with Rust.
After digging, the reason was quite simple, to be explained in comments.
This doesn't change our performance gains since, in the worst case (which is a weird case), it adds a constant number of potential extra values to already batched inverses. I reran the benchmarks to double-check, and the verification time numbers are the same.
With this fix, `go-verkle` using this branch passes all the tests correctly. :)

multiproof:  bug fix, we always need (t-z_i) inverses

---

bandersnatch/bandersnatch.go
bandersnatch/fr/element.go
banderwagon/element.go
banderwagon/element_test.go
common/common.go
common/transcript_test.go
ipa/barycentric_test.go
ipa/config.go
ipa/ipa_test.go
ipa/prover.go
ipa/verifier.go
multiproof.go
multiproof_test.go

This PR main goal is to remove existing panics in the database.
The changes can be understood in two buckets:
- Panics in tests: aren't that relevant, but I've changed them to `t.Fatal(f)`.
- Panics in logic: These are the most important ones; mostly had to change some further APIs to return errors.
Only one panic is left in a codepath that doesn't (and shouldn't) happen in real code. I still think we should solve it, and I go in decent length explaining which is it and why/how.
Fixes https://github.com/crate-crypto/go-ipa/issues/12
Fixes https://github.com/crate-crypto/go-ipa/issues/4

Remove panics

---

.github/workflows/bench.yml

This PR adds a GH action that generates a [historical timeline](https://crate-crypto.github.io/go-ipa/dev/bench/) and a [per-action run](https://discord.com/channels/@me/1080044502271672341/1148947438086930454) report of existing benchmarks on every merge to `master`.
We use free CI machines, so things can be somewhat noisy for activating automatic alerting without setting an absurd threshold of 40%. We can try to watch plots occasionally and see if this is useful.
I had to manually create a `gh-pages` branch to prepare a bit of the stage for the action to push the generated website to the GH pages automatically.
Context: [I've discovered a gnark-crypto perf regression](https://github.com/Consensys/gnark-crypto/pull/441) while experimenting with an idea in this repo while running …

ci: add benchmark report generation

---

ipa/ipa_test.go
ipa/prover.go
ipa/verifier.go

This PR adds handling for correctly generating proofs and verifying them if the evaluation point is inside the domain.
Technically speaking, this is a border-case of multiproofs for Verkle Trees. In Multiproofs, we use IPA to evaluate an "aggregated polynomial" at a random scalar field element via FS. This means that the chance of getting an in-domain evaluation point is `256/FrSize` which is incredibly low but still possible. 
If, by any chance, this happens in the current implementation, our prover/verifier would fail since the barycentric formula needs the assumption that the evaluation point is outside the domain.
The solution to this is straightforward and is to not really on the barycentric formula for the B vector and use a ~unity vector (i.e: [0, 0,.., 1,.., 0]). The reason this …

ipa: support in-domain evaluations

---

bandersnatch/bandersnatch.go
banderwagon/precomp.go

*Thanks to Gottfried Herold for suggesting this change* *in a chat we had some time ago*.
This PR improves the performance of our fixed-basis MSM algorithm, which is used for most heavy cryptography operations (e.g: tree key hashing, vector commitments, etc.).
The idea is simple: use Extended points additions instead of Projective mixed additions when we aggregate the precomputed points. That saves finite-field muls, thus improving performance. It has a 50% memory cost, but considering some improvements we did a while ago (and other ideas that we can still use), it feels justified for this speedup.
The path to doing this was longer than expected since I had to do some things before to be ready for the change:
- Stop relying on generated code and directly on gnark-crypto, which already …

precomp: use normalized extended points

---

banderwagon/element.go
banderwagon/element_test.go
common/transcript.go
common/transcript_test.go
ipa/ipa_test.go
ipa/prover.go
ipa/verifier.go
multiproof.go
multiproof_test.go

This PR improves the performance of the proof generator and verifier.
There were many changes that I'll describe below.
Optimizations that improved the performance of **both** the prover and verifier:
- **Avoid a lot of Fiat-Shamir transcript allocations**: For labels, we used `strings`, which eventually needed to escape to the heap since the `Hasher` requires `[]bytes`. Also, the labels are fixed (e.g: `C`, `w`, `t`, `L`, `R`, and domain separators) which doesn't even make sense that they escape once per transcript write. (e.g: for 100k points, we'd be escaping to the heap constant strings). This could be easily fixed by defining constant and not requiring `strings` since the hasher doesn't mutate their values.
- **Include buffering in Fiat-Shamir transcript**: for many openings (i.e: …

multiproof: improve performance of prover and verifier

---

go.mod
go.sum

This PR updates `gnark-crypto`.
I did a bench comparison, and looks like there aren't any _relevant_ regressions.
Output:
```
name                                     old time/op    new time/op    delta
pkg:github.com/crate-crypto/go-ipa goos:linux goarch:amd64
ProofGeneration/numopenings=2000-16        52.4ms ± 1%    52.8ms ± 1%    ~     (p=0.151 n=5+5)
ProofGeneration/numopenings=16000-16       77.6ms ± 1%    76.9ms ± 0%    ~     (p=0.310 n=5+5)
ProofGeneration/numopenings=32000-16       98.2ms ± 1%    97.8ms ± 2%    ~     (p=0.421 n=5+5)
ProofGeneration/numopenings=64000-16        151ms ± 5%     140ms ± 3%  -7.46%  (p=0.008 n=5+5)
ProofGeneration/numopenings=128000-16       243ms ± 6%     230ms ± 1%  -5.32%  (p=0.016 n=5+5)
ProofVerification/numopenings=2000-16      8.67ms ± 2% …
```

mod: update gnark-crypto

---

banderwagon/element.go
banderwagon/element_test.go

This PR adds an extra check in `banderwagon.SetBytesUncomprssed(..., true)` such that:
- Checks if the `x` coordinate corresponds to a point in the curve.
- Verifies that the resulting `y` coordinate bytes match the right-half of the provided bytes.
Tests were added to check both cases.

banderwagon: check point in curve in SetBytesUncompressed

---

go.mod
go.sum

This PR updates to the latest `gnark-crypto@v0.13.0`.
I've run the set of benchmarks compared to master, and don't see any regressions or similar.
```
name                                     old time/op    new time/op    delta
pkg:github.com/crate-crypto/go-ipa goos:linux goarch:amd64
ProofGeneration/numopenings=2000-16        35.4ms ± 0%    34.5ms ± 0%   ~     (p=1.000 n=1+1)
ProofGeneration/numopenings=16000-16       56.0ms ± 0%    55.0ms ± 0%   ~     (p=1.000 n=1+1)
ProofGeneration/numopenings=32000-16       75.7ms ± 0%    74.4ms ± 0%   ~     (p=1.000 n=1+1)
ProofGeneration/numopenings=64000-16        117ms ± 0%     117ms ± 0%   ~     (p=1.000 n=1+1)
ProofGeneration/numopenings=128000-16       203ms ± 0%     215ms ± 0%   ~     (p=1.000 n=1+1)
ProofVerification/numopenings=2000-16 …
```

mod: update to gnark-crypto v0.13.0
